### ISSUE TITLE
i cant using ARX API for anonymizing 

### ISSUE THREAD

**Issue by milad1370s** [arx-deidentifier/arx#104]
hello, i want to use ARX api and write sample that anonymize data with t-closeness, l diversity and k-anonymity but i have some error as follow:
Attribute 'age': hierarchy misses some values or contains duplicates
	at org.deidentifier.arx.framework.data.GeneralizationHierarchy.<init>(Unknown Source)
	at org.deidentifier.arx.framework.data.DataManager.<init>(Unknown Source)
	at org.deidentifier.arx.ARXAnonymizer.getDataManager(Unknown Source)
	at org.deidentifier.arx.ARXAnonymizer.anonymize(Unknown Source)
	at kanonytest.kanony.main(kanony.java:68)
i use the last version of ARX API.
can you help me? thanks a lot

**Comment by prasser** [comment]
Thanks for your interest in ARX!

This is likely not a bug but an expected error message. The hierarchy that you are using for the attribute age either (a) doesn't contain a generalization rule for one of the values appearing in the dataset (example: dataset contains age "99" but the value "99" is not contained in the hierarchy) or, (b) contains an ambiguous rule (example: "[10, 20[" can either be mapped to "[0, 20[" or "[10, 30[").

I hope this helps,
Fabian

P.S.: Please direct further questions on the usage of ARX to arx.deidentifier@gmail.com
