### ISSUE TITLE
[BUG] Unexpected error thrown when running apply selected transformation

### ISSUE THREAD

**Issue by jubeormk1** [arx-deidentifier/arx#414]
**Describe the bug**

``java.lang.RuntimeException: java.lang.IllegalArgumentException`` thrown when pressing "apply selected transformation" ([0,0])

**To Reproduce**
1. Open the project 'UJIIndoorLocTrain_Map.deid'
2. Select "Configure Transformation" Tab
3. Click on Edit > Anonymize
4. Accept the default parameters
5. Select "Analyse utility" tab
6. Click on "apply selected transformation"
7. If an error dialog is not shown, repeat 6.
8. See error

**Expected behavior**
That the selected transformation gets applied to the input data and shown in the output data.

**Screenshots**
![image](https://user-images.githubusercontent.com/48457722/190906777-964d63cb-586c-4f60-bcfe-e95c3505568d.png)

**ARX GUI (please complete the following information):**
 - OS: Windows 11
 - Version [e.g. 3.9.0]

**Additional context**

project file:
[UJIIndoorLocTrain_Map.zip](https://github.com/arx-deidentifier/arx/files/9594111/UJIIndoorLocTrain_Map.zip)

Exception thrown:
```
java.lang.RuntimeException: java.lang.IllegalArgumentException: Invalid value: '-7685.72349999845' or '-7685.72349999845'
	at org.deidentifier.arx.DataHandleOutput.internalCompare(Unknown Source)
	at org.deidentifier.arx.DataRegistry$1.compare(Unknown Source)
	at cern.colt.GenericSorting.mergeSort(Unknown Source)
	at cern.colt.GenericSorting.mergeSort(Unknown Source)
	at cern.colt.GenericSorting.mergeSort(Unknown Source)
	at cern.colt.GenericSorting.mergeSort(Unknown Source)
	at cern.colt.GenericSorting.mergeSort(Unknown Source)
	at cern.colt.GenericSorting.mergeSort(Unknown Source)
	at cern.colt.GenericSorting.mergeSort(Unknown Source)
	at cern.colt.GenericSorting.mergeSort(Unknown Source)
	at cern.colt.GenericSorting.mergeSort(Unknown Source)
	at cern.colt.GenericSorting.mergeSort(Unknown Source)
	at cern.colt.GenericSorting.mergeSort(Unknown Source)
	at cern.colt.GenericSorting.mergeSort(Unknown Source)
	at cern.colt.GenericSorting.mergeSort(Unknown Source)
	at org.deidentifier.arx.DataRegistry.sortAll(Unknown Source)
	at org.deidentifier.arx.DataRegistry.sort(Unknown Source)
	at org.deidentifier.arx.DataRegistry.sort(Unknown Source)
	at org.deidentifier.arx.DataHandle.sort(Unknown Source)
	at org.deidentifier.arx.gui.Controller.updateViewConfig(Unknown Source)
	at org.deidentifier.arx.gui.Controller.actionApplySelectedTransformation(Unknown Source)
	at org.deidentifier.arx.gui.view.impl.MainWindow$20.action(Unknown Source)
	at org.deidentifier.arx.gui.view.impl.MainToolBar$1.widgetSelected(Unknown Source)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4213)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1037)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4030)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3630)
	at org.deidentifier.arx.gui.Main.main(Unknown Source)
	at org.deidentifier.arx.gui.Main.main(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Invalid value: '-7685.72349999845' or '-7685.72349999845'
	at org.deidentifier.arx.DataType$ARXDecimal.compare(Unknown Source)
	... 31 more
Caused by: java.lang.IllegalArgumentException: For input string: ".7726384929998804959998385E47726384929998804959998385E4": -7685.72349999845
	at org.deidentifier.arx.DataType$ARXDecimal.parse(Unknown Source)
	... 32 more
Caused by: java.lang.NumberFormatException: For input string: ".7726384929998804959998385E47726384929998804959998385E4"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.base/java.lang.Double.parseDouble(Double.java:549)
	at java.base/java.text.DigitList.getDouble(DigitList.java:169)
	at java.base/java.text.DecimalFormat.parse(DecimalFormat.java:2198)
	... 33 more

```

**Comment by prasser** [comment]
Thanks for reporting this. I think this has already been resolved in the current master branch as part of another bugfix. Can you build ARX from source and try the current master branch?

**Comment by idhamari** [comment]
I can not reproduce the error. I think it is fixed!

**Comment by prasser** [comment]
Thx
