### ISSUE TITLE
[BUG] Error when using more than 64 quasi-identifiers

### ISSUE THREAD

**Issue by marcheschi** [arx-deidentifier/arx#462]
**Describe the bug**
Hi I tried to set all columns as quasi-identifying and only 4 columns with a hierarchy defined, but I receive an internal error:
java.lang.NullPointerException: Cannot load from object array because "this.hierarchy2" is null
	at org.deidentifier.arx.framework.check.transformer.Transformer12.processGroupify(Unknown Source)
	at org.deidentifier.arx.framework.check.transformer.AbstractTransformer.call(Unknown Source)
	at org.deidentifier.arx.framework.check.Transformer.applyInternal(Unknown Source)
	at org.deidentifier.arx.framework.check.Transformer.applyRollup(Unknown Source)
	at org.deidentifier.arx.framework.check.TransformationChecker.check(Unknown Source)
	at org.deidentifier.arx.framework.check.TransformationChecker.check(Unknown Source)
	at org.deidentifier.arx.algorithm.FLASHAlgorithmImpl.checkAndTag(Unknown Source)
	at org.deidentifier.arx.algorithm.FLASHAlgorithmImpl.checkPath(Unknown Source)
	at org.deidentifier.arx.algorithm.FLASHAlgorithmImpl.binarySearch(Unknown Source)
	at org.deidentifier.arx.algorithm.FLASHAlgorithmImpl.traverse(Unknown Source)
	at org.deidentifier.arx.ARXAnonymizer.anonymize(Unknown Source)
	at org.deidentifier.arx.ARXAnonymizer.anonymize(Unknown Source)
	at org.deidentifier.arx.gui.worker.WorkerAnonymize.run(Unknown Source)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

we have an excel with 74 columns.

**Screenshots**
.
![image](https://github.com/user-attachments/assets/3e628fcb-4fa3-4086-ac7c-59342eec71a4)

**ARX GUI (please complete the following information):**
 - OS:  Windows
 - Version  3.9.1

if I use less columns it works maybe is a Bug.

Is it mandatory to define all hierarchy of quasi-identifiers?
Thank you
Paolo

**Comment by prasser** [comment]
This is a bug and should not happen. Are you able to provide something to us (project file or code) to reproduce this?

**Comment by marcheschi** [comment]
I'll try, but I cannot send the actual project.
As soon as I have a usable file I will send to you, do you have a place where I can send it? (sftp,... )
Thank you
Paolo

**Comment by prasser** [comment]
If it's sensitive we can set something up. Otherwise, post here or send via email: fabian.prasser@charite.de

**Comment by prasser** [comment]
Thanks for sending the project. I was not able to get a first understanding of the problem.

The bug is triggered when more than 64 quasi-identifiers are being used.

Generally, it will be very hard in most cases to anonymize a dataset with that many quasi-identifiers defined. So a workaround would be, to come up with an anonymization concept that assumes <= 64 quasi-identifiers (max. 10-20 is a common recommendation).

We will still take a closer look and fix this.

**Comment by prasser** [comment]
Some further info: The underlying issue is that ARX internally uses 64 bit masks to keep track of which modifications are needed for which quasi-identifiers. Hence, fixing this would require changes very deeply at the core runtime environment of ARX, which can also have measurable impacts on execution times. As anonymizing data with >64 quasi-identifiers likely won't work anyways, we will probably simply prevent such configurations from being executed.

**Comment by prasser** [comment]
Fix committed with a93eeff. Closing.
